name: Publish CI

on:
    workflow_dispatch:
      inputs:
        label:
          description: 'Label'
          default: 'Npm Publish - Version Update'
        logLevel:
          description: 'Log level'
          required: true
          default: 'warning'

jobs:
  build:
    runs-on: ubuntu-latest

    if: github.actor == github.event.repository.owner.login

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - name: Input
      run: |
        echo label: ${{ github.event.inputs.label }}
    - uses: actions/checkout@v3
      with:
        ref: dev
    - name: Node Dependencies for CLI
      run: |
        npm install -g @thzero/library_cli
    - name: Node Dependencies
      run: |
        npm install --no-package-lock
    - name: Package Output
      run: |
        cat package.json
    - name: Initialize Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        registry-url: 'https://registry.npmjs.org'
    - run: npm publish --access public
      if: steps.git-changes.outputs.changed == 1 && success()
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}